language: ruby
rvm:
  - "2.6.0"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rails db:create db:migrate --trace
  - bundle exec rails test
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database mydb_test'
bundler_args: --binstubs=./bundler_stubs